Trying to figure out why this isn't on the path

diff --git a/executable-monitor/action.yml b/executable-monitor/action.yml
--- a/executable-monitor/action.yml
+++ b/executable-monitor/action.yml
@@ -28,21 +28,35 @@ inputs:
 runs:
   using: "composite"
   steps: 
-      - name: Install Dependencies
+      - env:
+          # The bash escape character is \033
+          # At time of writing, you can't add a global environment to an
+          # action so stuck with this. If this gets changed please move this
+          bashPass:   \033[32;1mPASSED -
+          bashInfo:   \033[33;1mINFO -
+          bashFail:   \033[31;1mFAILED -
+          bashEnd:     ${{ env.bashEnd }}
+          stepName: Install Dependencies
+        name: ${{ env.stepName }}
+        shell: bash
         run: |
-          # Install Dependencies
+          # ${{ env.stepName }}
           echo "::group::Install Dependencies"
           pip install -r $GITHUB_ACTION_PATH/requirements.txt
+          exitStatus=$?
           echo "::endgroup::"
-          if [ "$?" = "0" ]; then
-            echo -e "\033[32;3mInstalled all dependencies\033[0m"
-            exit 0
-          else
-            echo -e "\033[32;31mDependencies Install failed...\033[0m"
+          if [ $exitStatus -eq 1 ]; then
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            set -e
             exit 1
+          else
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 0
           fi
+        
+      - env:
+          stepName: ${{ env.stepName }}
         shell: bash
-      - name: Run Executable with Monitoring
         run: |
           # Run Executable with Monitoring
           echo "::group::Argument Parsing"
@@ -50,7 +64,7 @@ runs:
           # Make sure we have an exit condition to look for
           if [ "${{ inputs.success-exit-code }}" = "" ] && [ "${{ inputs.success-line }}" = "" ]; then
             echo "::endgroup::"
-            echo -e "\033[32;31mDid not supply an input of success-line or success-exit-code to search for\033[0m"
+            echo -e "${{ env.bashFail}}Did not supply an input of success-line or success-exit-code to search for ${{ env.bashEnd }}"
             exit 1
           fi
 
@@ -84,12 +98,12 @@ runs:
             successLineArgs="--success-line=\"${{ inputs.success-line}}\" $optArgs"
             echo "Adding --success-line=${{ inputs.success-line}}"
             echo "::endgroup::"
-            echo -e "\033[1;33mRunning Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --success-line="${{ inputs.success-line }}" $optArgs  \033[0m"
+            echo -e " ${{ env.bashInfo }}Running Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --success-line="${{ inputs.success-line }}" $optArgs ${{ env.bashEnd }}"
             echo "::group::Executable Output"
             python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs --success-line="${{ inputs.success-line}}"
           else
             echo "::endgroup::"
-            echo -e "\033[1;33mRunning Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs \033[0m"
+            echo -e " ${{ env.bashInfo }}Running Command: python3 executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs ${{ env.bashEnd }}"
             echo "::group::Executable Output"
             python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} $optArgs
           fi
@@ -97,11 +111,10 @@ runs:
           exitStatus=$?
           echo "::endgroup::"
           if [ "$exitStatus" = "0" ]; then
-            echo -e "\033[32;3mValid exit status found\033[0m"
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
             exit 0
           else
-            echo -e "\033[32;31mDid not find a valid exit condition\033[0m"
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
             set -e
             exit 1
           fi
-        shell: bash
diff --git a/formatting/action.yml b/formatting/action.yml
--- a/formatting/action.yml
+++ b/formatting/action.yml
@@ -6,13 +6,18 @@ inputs:
     required: false
     default: ./
   exclude-files:
-    description: 'List of comma-separated files to exclude from trailing whitespace check. Eg file1,file2'
+    description: 'List of comma-separated files to exclude from the formatting check. Eg file1,file2'
     required: false
     default: ''
   exclude-dirs:
-    description: 'List of comma-separated directories to exclude from trailing whitespace formatting check. Eg docs,build'
+    description: 'List of comma-separated directories to exclude from the formatting check. Eg docs,build'
     required: false
     default: ''
+  include-extensions:
+    description: 'List of comma-separated extensions to add to the formatting check . Eg md,dox'
+    required: false
+    default: ''
+
 runs:
   using: "composite"
   steps:
@@ -23,8 +28,44 @@ runs:
         run: |
           # ${{ env.stepName }}
           echo "::group::${{ env.stepName }}"
-          sudo apt-get install clang-format
+          sudo apt-get install clang-format fd-find
+          ls $GITHUB_ACTION_PATH/../helpers
+          echo -e "$GITHUB_ACTION_PATH/../helpers" >> $GITHUB_PATH
+          export GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH/../helpers
+
+          fdfind --version
+          fdInstalled=$?
+
+          clang-format --version
+          clangFormatInstalled=$?
+
+          set +e
+          echo -e "getFilesAdded= $getFilesAdded"
+          echo -e "GITHUB_ACTION_PATH= $GITHUB_ACTION_PATH"
+          echo -e "ls GITHUB_ACTION_PATH = $(ls $GITHUB_ACTION_PATH)"
+          echo -e "ls GITHUB_ACTION_PATH/.. = $(ls $GITHUB_ACTION_PATH/..)"
+          echo -e "pwd= $(pwd)";
+          echo -e "ls (pwd)/../= $(ls $(pwd)/../)";
+          echo -e "ls $(pwd)/../helpers= $(ls $(pwd)/../helpers)";
+          echo -e "$(pwd)/../helpers" >> $GITHUB_PATH
+          echo "$(readlink -f ../helpers)" >> $GITHUB_PATH
+          echo "PATH=$PATH"
+          export PATH="$(pwd)/../helpers"
+          echo "PATH=$PATH"
+          set -e
+
+          getFiles --help
+          getFilesAdded=$?
+          echo -e "getFilesAdded=$getFilesAdded"
+
           echo "::endgroup::"
+          if [ $getFilesAdded -eq 1 ] || [ $clangFormatInstalled -eq 1] || [ $fdInstalled -eq 1 ]; then
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 1
+          else
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 0
+          fi
 
       - env:
           stepName: Validate Inputs
@@ -41,21 +82,11 @@ runs:
         shell: bash
         run: |
           # ${{ env.stepName }}
-          set +e
-          exitStatus=0
           # Check exclude dirs for possible input issues
-          if [[ "${{ inputs.exclude-dirs }}" = *" "* ]]; then
-            echo -e "${{ env.bashFail }} YOU HAVE WHITESPACE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
+          if [[ "${{ inputs.exclude-dirs }}" = *"\n"* ]]; then
+            echo -e "${{ env.bashFail }} YOU HAVE NEWLINE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
             exitStatus=1
           fi
-
-          # Check exclude-files  for possible input issues
-          if [[ "${{ inputs.exclude-files }}" = *" "* ]]; then
-            echo -e "${{ env.bashFail }} YOU HAVE WHITESPACE IN YOUR EXCLUDE-FILES. ${{ env.bashEnd }}"
-            exitStatus=1
-          fi
-          set -e
-          exit $exitStatus
 
       - env:
           stepName: Run Clang Format
@@ -72,13 +103,11 @@ runs:
           # This would mean the first time a file fails the check that we exit without formatting all files.
           set +e
 
-          # Get all files that end in .c or .h.
-          # Exclude any files or directories that we were asked to.
-          # Then limit the search to files that have the amazon copyright on them.
-          # -l Provides a list of the files
-          # -r Means do a recursive search
-          # -i tells it to ignore the case
-          files=$(grep --include={*.[ch],} --exclude={${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},} -lriE "copyright (.*) [0-9]{4} amazon.com" )
+          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
+          if [ ! $? -eq 0 ]; then
+              echo -e "${{ env.bashFail }} Error calling getFiles() ${{ env.bashEnd }}"
+              echo -e "$fileOut"
+          fi
 
           # Loop over the files that matched the above conditions
           for file in ${files[@]}; do
@@ -89,23 +118,24 @@ runs:
             # This way we can print the command only if it fails
             fileOut=$(clang-format -i --verbose --style=file $file)
             # If the previous command failed then print out an error message as well as the output
-            if [ "$?" != "0" ]; then
+            if [ ! $? -eq 0 ]; then
               echo -e "${{ env.bashFail }} Error parsing "$file" ${{ env.bashEnd }}"
               echo -e "$fileOut"
             fi
           done
+
           echo "::endgroup::"
           # Run a git diff to print the differences if any exist, return an error code if there are any
+
           echo "::group::File Difference"
           git diff --exit-code
-          exitCode=$?
           echo "::endgroup::"
-          if [ "$exitCode" = "0" ]; then
+          exitCode=$?
+          if [ $exitCode -eq 0 ]; then
             echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
           else
-            filesWithErrors=$(git diff --name-only)
             echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
-            echo -e "${{ env.bashFail }} "$filesWithErrors" ${{ env.bashEnd }} "
+            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
             echo -e "${{ env.bashFail }} ${{env.stepName }} ${{ env.bashEnd }}"
             # If there is an error, set this flag high again so the exit 1 fails the run instantly
             set -e
@@ -123,9 +153,21 @@ runs:
         working-directory: ${{ inputs.path }}
         run: |
           # ${{ env.stepName }}
+          echo "::group::${{ env.stepName }}"
+
           set +e
-          grep --exclude={README.md,${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},.git} -rnIe "[[:blank:]]$" .
-          if [ "$?" = "0" ]; then
+          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
+
+          for file in ${files[@]}; do
+            grep -nIe "[[:blank:]]$" "$file" > $fileOut
+            if [ $? -eq 0 ]; then
+              echo "${{ env.bashFail }} "$fileOut" ${{ env.bashEnd }}"
+              exitStatus=1;
+            fi
+          done
+
+          echo "::endgroup::"
+          if [ $exitStatus -eq 1 ]; then
             echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
             set -e
             exit 1
@@ -143,8 +185,16 @@ runs:
         run: |
           # ${{ env.stepName }}
           set +e
-          grep --exclude={${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},.git} -rnl $'\r'
-          if [ "$?" = "0" ]; then
+
+          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
+          for file in ${files[@]}; do
+            grep -nl $'\r' "$file" > $fileOut
+            if [ $? -eq 0 ]; then
+              echo "${{ env.bashFail }} "$fileOut" ${{ env.bashEnd }}"
+              exitStatus=1;
+            fi
+          done
+          if [ $exitStatus -eq 1 ]; then
             echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
             set -e
             exit 1
diff --git a/spellings/action.yml b/spellings/action.yml
--- a/spellings/action.yml
+++ b/spellings/action.yml
@@ -13,8 +13,8 @@ inputs:
     description: 'List of comma-separated directories to exclude from trailing whitespace formatting check. Eg docs,build'
     required: false
     default: ''
-  include-files:
-    description: 'List of comma-separated files to include into the spell check. Eg docs,build'
+  include-extensions:
+    description: 'List of comma-separated file endings to include into the spell check. Eg md, dox, build'
     required: false
     default: ''
 
@@ -23,7 +23,12 @@ runs:
   steps:
       - env:
           stepName: Install Spell
+          bashPass:   \033[32;1mPASSED -
+          bashInfo:   \033[33;1mINFO -
+          bashFail:   \033[31;1mFAILED -
+          bashEnd:    \033[0m
         name: ${{ env.stepName }}
+        shell: bash
         run: |
           #  ${{ env.stepName }}
           echo "::group::${{ env.stepName }}"
@@ -31,13 +36,19 @@ runs:
           sudo apt-get install util-linux
           sudo apt-get install npm
           npm install -g cspell
+          echo "$GITHUB_ACTION_PATH/../helpers" >> $GITHUB_PATH
+          cspell --version
+          exitStatus=$?
+          set -e
           echo "::endgroup::"
-        shell: bash
+          if [ $exitStatus -eq 0 ]; then
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+            exit 1
+          fi
+
       - env:
-          bashPass:   \033[32;1mPASSED -
-          bashInfo:   \033[33;1mINFO -
-          bashFail:   \033[31;1mFAILED -
-          bashEnd:    \033[0m
           stepName: Check Spelling
         name: ${{ env.stepName}}
         shell: bash
@@ -46,25 +57,12 @@ runs:
           #  ${{ env.stepName }}
           echo "::group::${{ env.stepName }}"
           set +e
-          pwd
-          ls $GITHUB_ACTION_PATH
-          readlink -f "$GITHUB_ACTION_PATH"/../.
-          export PATH=$(readlink -f "$GITHUB_ACTION_PATH"/../.):$PATH
-          file=$(getFiles --exclude-dirs="${{ inputs.exclude-dirs }}" --exclude-files=${{ inputs.exclude-files }} --include-files= ${{ inputs.include-files}})
-          #files=($(grep --include={*.[ch],} --exclude={${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},} -lriE "copyright (.*) [0-9]{4} amazon.com" ))
-          for file in ${files[@]}; do
-            echo -e "${{ env.bashInfo }} Checking Spelling of: "$file" ${{ env.bashEnd }}"
-            # Call cspell with the C language option. 
-            # Enable colour output
-            # Use the config file in the repository calling it
-            # Show suggestions for correct spellings
-            # Check Spelling of words in file
-            cspell --language-id C --color -c cspell.config.yaml --show-suggestions --show-context $file
-          done
+          files=$(getFiles --exclude-dirs="${{ inputs.exclude-dirs }}" --exclude-files=${{ inputs.exclude-files }} --include-extensions=${{ inputs.include-extensions}})
+          cspell --language-id C --color -c cspell.config.yaml --show-suggestions --show-context --file-list "$file"
           exitStatus=$?
           set -e
           echo "::endgroup::"
-          if [ "$exitStatus" = "0" ]; then
+          if [ $exitStatus -eq 0 ]; then
             echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
           else
             echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
