Welp can't do the matrix. Can make a duplicate job run that uses clang formatting though

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,21 +15,8 @@ env:
   bashEnd:    \033[0m
 
 jobs:
-  formatting-error-cases:
-    strategy:
-      fail-fast: false
-      matrix:
-          inputs: [
-            {
-              osVersion: ubuntu-latest,
-              formattingVersion: ./clang-formatting,
-            },
-            {
-             osVersion: ubuntu-20.04,
-             formattingVersion: ./formatting,
-            },
-          ]
-    runs-on: ${{ matrix.inputs.osVersion }}
+  uncrustify-formatting-error-cases:
+    runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v3
       - env:
@@ -37,7 +24,7 @@ jobs:
         name: ${{ env.stepName }}
         id: all-format-errors
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
 
@@ -46,7 +33,7 @@ jobs:
         name: ${{ env.stepName }}
         id: crlf-and-format-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithTrailingWhitespace"
@@ -56,7 +43,7 @@ jobs:
         name: ${{ env.stepName }}
         id: crlf-and-whitespace-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrors"
@@ -66,7 +53,7 @@ jobs:
         name: ${{ env.stepName }}
         id: crlf-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrors,filesWithCRLFEndings,filesWithTrailingWhitespace"
@@ -77,7 +64,7 @@ jobs:
         name: ${{ env.stepName }}
         id: formatting-and-whitespace-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithCRLFEndings"
@@ -87,7 +74,7 @@ jobs:
         name: ${{ env.stepName }}
         id: formatting-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithTrailingWhitespace,filesWithCRLFEndings"
@@ -97,7 +84,7 @@ jobs:
         name: ${{ env.stepName }}
         id: whitespace-error
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrrors,filesWithCRLFEndings"
@@ -107,7 +94,7 @@ jobs:
         name: ${{ env.stepName }}
         id: error-in-exclude-dirs
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrrors,    filesWithCRLFEndings"
@@ -117,7 +104,7 @@ jobs:
         name: ${{ env.stepName }}
         id: error-in-exclude-files
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-files: "filesWithFormattingErrrors,    filesWithCRLFEndings"
@@ -127,7 +114,182 @@ jobs:
         name: ${{ env.stepName }}
         id: error-in-both
         continue-on-error: true
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
+        with:
+          path: formatting
+          exclude-files: "filesWithFormattingErrrors,    filesWithCRLFEndings"
+          exclude-dirs: "filesWithFormattingErrrors,
+                          filesWithCRLFEndings"
+
+      - env:
+          stepName: Check Failure Test Cases
+        name: ${{ env.stepName }}
+        id: check-failure-test-cases
+        shell: bash
+        run: |
+          # Check Failure Test Cases
+          exitStatus=0
+          if [ "${{ steps.all-format-errors.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Whitespace, CRLF, and Format Failure |  Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Whitespace, CRLF, and Format Failure | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.crlf-and-format-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | CRLF and Formatting Error | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | CRLF and Formatting Error | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.crlf-and-whitespace-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | CRLF and Whitespace Error | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | CRLF and Whitespace Error | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.crlf-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | CRLF Error | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | CRLF Error | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.formatting-and-whitespace-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Formatting and Whitespace Errror | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Formatting and Whitespace Errror | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.formatting-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Formatting Errror | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Formatting Errror | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.whitespace-error.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} Functional | Failure | Whitespace Errror | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} Functional | Failure | Whitespace Errror | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.error-in-exclude-dirs.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} API | Failure | Exclude Dirs Error | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} API | Failure | Exclude Dirs Error | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.error-in-exclude-files.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} API | Failure | Exclude Files Error | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} API | Failure | Exclude Files Error | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          if [ "${{ steps.error-in-both.outcome}}" = "failure" ]; then
+            echo -e "${{ env.bashPass }} API | Failure | Exclude Option Errors | Had Expected "failure" ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} API | Failure | Exclude Option Errors | Had Unexpected "success" ${{ env.bashEnd }}"
+            exitStatus=1
+          fi
+          exit $exitStatus
+  clang-formatting-error-cases:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - env:
+          stepName: "Functional | Failure | Whitespace, CRLF, and Format Failure"
+        name: ${{ env.stepName }}
+        id: all-format-errors
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+
+      - env:
+          stepName: "Functional | Failure | CRLF and Formatting Error"
+        name: ${{ env.stepName }}
+        id: crlf-and-format-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithTrailingWhitespace"
+
+      - env:
+          stepName: "Functional | Failure | CRLF and Whitespace Error"
+        name: ${{ env.stepName }}
+        id: crlf-and-whitespace-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrors"
+
+      - env:
+          stepName: "Functional | Failure | CRLF Error"
+        name: ${{ env.stepName }}
+        id: crlf-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrors,filesWithCRLFEndings,filesWithTrailingWhitespace"
+          exclude-files: "badFile.c"
+
+      - env:
+          stepName: "Functional | Failure | Formatting and Whitespace Errror"
+        name: ${{ env.stepName }}
+        id: formatting-and-whitespace-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithCRLFEndings"
+
+      - env:
+          stepName: "Functional | Failure | Formatting Errror"
+        name: ${{ env.stepName }}
+        id: formatting-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithTrailingWhitespace,filesWithCRLFEndings"
+
+      - env:
+          stepName: "Functional | Failure | Whitespace Errror"
+        name: ${{ env.stepName }}
+        id: whitespace-error
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrrors,filesWithCRLFEndings"
+
+      - env:
+          stepName: "API | Failure | Exclude Dirs Error"
+        name: ${{ env.stepName }}
+        id: error-in-exclude-dirs
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrrors,    filesWithCRLFEndings"
+
+      - env:
+          stepName: "API | Failure | Exclude Files Error"
+        name: ${{ env.stepName }}
+        id: error-in-exclude-files
+        continue-on-error: true
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-files: "filesWithFormattingErrrors,    filesWithCRLFEndings"
+
+      - env:
+          stepName: "API | Failure | Exclude Option Errors"
+        name: ${{ env.stepName }}
+        id: error-in-both
+        continue-on-error: true
+        uses: ./clang-formatting
         with:
           path: formatting
           exclude-files: "filesWithFormattingErrrors,    filesWithCRLFEndings"
@@ -204,29 +366,16 @@ jobs:
           fi
           exit $exitStatus
 
-  formatting-success-cases:
-    strategy:
-      fail-fast: false
-      matrix:
-          inputs: [
-            {
-              osVersion: ubuntu-latest,
-              formattingVersion: ./clang-formatting,
-            },
-            {
-             osVersion: ubuntu-20.04,
-             formattingVersion: ./formatting,
-            },
-          ]
-    runs-on: ${{ matrix.inputs.osVersion }}
-    steps:
+  uncrustify-formatting-success-cases:
+      runs-on: ubuntu-20.04
+      steps:
       - uses: actions/checkout@v3
-      
+
       - env:
           stepName: "Functional | Success | Exclude All Error Dirs"
         name: ${{ env.stepName }}
         id: exclude-dirs-with-errors
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrors,filesWithCRLFEndings,filesWithTrailingWhitespace"
@@ -236,7 +385,7 @@ jobs:
           stepName: "Functional | Success | Exclude Files"
         name: ${{ env.stepName }}
         id: exclude-files-with-errors
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:  
           path: formatting
           exclude-dirs: ",,,"
@@ -246,7 +395,7 @@ jobs:
           stepName: "Functional | Success | Exclude File and Exclude Dirs"
         name: ${{ env.stepName }}
         id: exclude-single-dir-multiple-files
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
         with:
           path: formatting
           exclude-dirs: "goodFiles"
@@ -256,7 +405,52 @@ jobs:
           stepName: "Functional | Success | Exclude Files and Exclude Dirs"
         name: ${{ env.stepName }}
         id: exclude-two-files-two-dirs
-        uses: ${{ matrix.inputs.formattingVersion }}
+        uses: ./formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrors,filesWithTrailingWhitespace"
+          exclude-files: "test.c,cgc_error.h,main-blinky.c"
+
+  clang-formatting-success-cases:
+      runs-on: ubuntu-latests
+      steps:
+      - uses: actions/checkout@v3
+
+      - env:
+          stepName: "Functional | Success | Exclude All Error Dirs"
+        name: ${{ env.stepName }}
+        id: exclude-dirs-with-errors
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "filesWithFormattingErrors,filesWithCRLFEndings,filesWithTrailingWhitespace"
+          exclude-files: "badFile.c"
+
+      - env:
+          stepName: "Functional | Success | Exclude Files"
+        name: ${{ env.stepName }}
+        id: exclude-files-with-errors
+        uses: ./clang-formatting
+        with:  
+          path: formatting
+          exclude-dirs: ",,,"
+          exclude-files: "badFile.c,cgc_error.h,main-blinky.c,test.c"
+
+      - env:
+          stepName: "Functional | Success | Exclude File and Exclude Dirs"
+        name: ${{ env.stepName }}
+        id: exclude-single-dir-multiple-files
+        uses: ./clang-formatting
+        with:
+          path: formatting
+          exclude-dirs: "goodFiles"
+          exclude-files: "cgc_error.h,main-blinky.c,test.c"
+
+      - env:
+          stepName: "Functional | Success | Exclude Files and Exclude Dirs"
+        name: ${{ env.stepName }}
+        id: exclude-two-files-two-dirs
+        uses: ./clang-formatting
         with:
           path: formatting
           exclude-dirs: "filesWithFormattingErrors,filesWithTrailingWhitespace"
